# Classification

In [397]:
import pandas as pd

In [398]:
pd.read_csv('weight-height.csv')

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [399]:
df = pd.read_csv('weight-height.csv')

In [400]:
from sklearn.preprocessing import LabelEncoder

In [401]:
le=LabelEncoder()

In [402]:
le.fit_transform(df['Gender'])

array([1, 1, 1, ..., 0, 0, 0])

In [403]:
M1F0=le.fit_transform(df['Gender'])

In [404]:
df['gender M1F0'] = M1F0

In [405]:
df

      Gender     Height      Weight  gender M1F0
0       Male  73.847017  241.893563            1
1       Male  68.781904  162.310473            1
2       Male  74.110105  212.740856            1
3       Male  71.730978  220.042470            1
4       Male  69.881796  206.349801            1
...      ...        ...         ...          ...
9995  Female  66.172652  136.777454            0
9996  Female  67.067155  170.867906            0
9997  Female  63.867992  128.475319            0
9998  Female  69.034243  163.852461            0
9999  Female  61.944246  113.649103            0

[10000 rows x 4 columns]

In [406]:
df.drop(['Gender'],axis='columns')

         Height      Weight  gender M1F0
0     73.847017  241.893563            1
1     68.781904  162.310473            1
2     74.110105  212.740856            1
3     71.730978  220.042470            1
4     69.881796  206.349801            1
...         ...         ...          ...
9995  66.172652  136.777454            0
9996  67.067155  170.867906            0
9997  63.867992  128.475319            0
9998  69.034243  163.852461            0
9999  61.944246  113.649103            0

[10000 rows x 3 columns]

In [407]:
df

      Gender     Height      Weight  gender M1F0
0       Male  73.847017  241.893563            1
1       Male  68.781904  162.310473            1
2       Male  74.110105  212.740856            1
3       Male  71.730978  220.042470            1
4       Male  69.881796  206.349801            1
...      ...        ...         ...          ...
9995  Female  66.172652  136.777454            0
9996  Female  67.067155  170.867906            0
9997  Female  63.867992  128.475319            0
9998  Female  69.034243  163.852461            0
9999  Female  61.944246  113.649103            0

[10000 rows x 4 columns]

In [408]:
ndf=df.drop(['Gender','Weight'],axis='columns')

In [409]:
ndf

         Height  gender M1F0
0     73.847017            1
1     68.781904            1
2     74.110105            1
3     71.730978            1
4     69.881796            1
...         ...          ...
9995  66.172652            0
9996  67.067155            0
9997  63.867992            0
9998  69.034243            0
9999  61.944246            0

[10000 rows x 2 columns]

In [410]:
from sklearn.model_selection import train_test_split

In [411]:
x= ndf['Height']

In [412]:
y=ndf['gender M1F0']

In [413]:
X_train,X_test, y_train, y_test=train_test_split(ndf[['Height']],ndf['gender M1F0'],test_size=0.1,random_state=20)

In [414]:
ndf.shape

(10000, 2)

In [415]:
X_train

         Height
6706  64.450905
3527  71.695482
1485  70.340936
974   69.876633
5450  62.750997
...         ...
3915  67.624276
9620  66.915077
7068  64.628295
7391  63.505894
4367  69.105846

[9000 rows x 1 columns]

In [416]:
y_train

6706    0
3527    1
1485    1
974     1
5450    0
       ..
3915    1
9620    0
7068    0
7391    0
4367    1
Name: gender M1F0, Length: 9000, dtype: int32

In [417]:
X_test

         Height
9957  62.903719
1687  73.748751
2116  64.336793
231   71.968306
2780  67.786333
...         ...
4596  71.368891
5214  56.785434
6124  65.420183
6258  70.544306
869   67.697104

[1000 rows x 1 columns]

In [418]:
from sklearn.linear_model import LogisticRegression

In [419]:
model = LogisticRegression()

In [420]:
model.fit(X_train,y_train)

LogisticRegression()

In [421]:
model.predict(X_test)

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1])

In [422]:
model.score(X_test,y_test)

0.837